[package]
name = "rv1106-examples"
version = "0.0.1"
edition = "2021"
description = "rv110x example code and tests."
publish = false

[dependencies]
webpki-roots = "0.26"
rustls = {version = "0.23.23"}
rv1106-sys = { path = "../rv1106-sys" }
tokio = { version = "1", features = ["full"] }
